#include <psys.h>

#define NTITLE		"#nodeTitle"
#define NNAME		"#nodeName"
#define NID		"#nodeId"
#define BROOM		"#baseRoom"
#define MFLOOR		"#MainFloor"
#define ULWIDTH		"#UNLOGGED-WIDTH"
#define ECD_DEFAULT	"#ECD-DEFAULT"
#define ISDOOR		"#ISDOOR"
#define SYSOP		"#sysopName"
#define SYSOPMARC	"#SYSOP-ARCHIVE"
#define SYSOPPASS	"#sysPassword"
#define DISKFREE	"#DISK-FREE"
#define CRYPT		"#CRYPTSEED"

#define AIDESP		"#AIDESEEALL"
#define LOGINP		"#LOGINOK"
#define ULENTRY		"#ENTEROK"
#define ROOMCP		"#ROOMOK"
#define READOK		"#READOK"
#define ALLMAIL		"#ALLMAIL"
#define DOORP		"#DoorPrivs"
#define ANONML		"#ANON-MAIL-LENGTH"
#define LATTEMPTS	"#LOGIN-ATTEMPTS"
#define FPRIVS		"#FILE-PRIV-DEFAULT"
#define CLEANCLOG	"#CLEAN-CALLLOG"
#define ANONSESSIONS	"#ANONYMOUS-SESSIONS"
#define AUTOMODERATE	"#AUTO-MODERATORS"
#define CONBANNERS	"#NO-CONSOLE-BANNER"
#define MAXMSGS		"#MAX-MSGS-ENTERED"
#define PARA_LOGIN	"#PARANOID-LOGIN"

#define OEDITOR		"#EDITOR"
#define EDITAREA	"#EDIT-AREA"

#define OLDVIDEO	"#OLDVIDEO"
#define CONTIMEOUT	"#CONSOLE-TIMEOUT"

#define PIBM		"#IBM"
#define COMPORT		"#COM"
#define SYSBAUD		"#SYSBAUD"
#define ENABLE		"#ENABLE-MODEM"
#define DISABLE		"#DISABLE-MODEM"
#define MDMSETUP	"#modemSetup"
#define NETPREF		"#callOutPrefix"
#define NETSUFFIX	"#callOutSuffix"
#define REINIT		"#REINIT"
#define D300		"#DialOut300"
#define D1200		"#DialOut1200"
#define D2400		"#DialOut2400"
#define D4800		"#DialOut4800"
#define D9600		"#DialOut9600"
#define D14400		"#DialOut14400"
#define D19200		"#DialOut19200"
#define D38400		"#DialOut38400"
#define D56800		"#DialOut56800"

#define NETENABLE	"#NETWORK"
#define NETLOC		"#NETAREA"
#define NDOMAIN		"#nodeDomain"
#define DOMAINDISP	"#DomainDisplay"
#define DOMLOC		"#DOMAINAREA"
#define DOMSERVE	"#ServeDomain"
#define MAILHUB		"#MailHub"
#define SIEGENET	"#SIEGENET"
#define ARCHIVE_WIDTH	"#ARCHIVE-WIDTH"
#define BANNER_COUNT	"#BANNER-COUNT"
#define NETDFT		"#NewNetPrivs"
#define SHAREDROOMS	"#SHARED-ROOMS"
#define SCANNET		"#SCAN-NET-MESSAGES"
#define NETRECEPT	"#NET_RECEPT_AREA"
#define NETAREASIZE	"#NET_AREA_SIZE"
#define MAXNETFILE	"#MAX_NET_FILE"
#define MAXUNSTABLE	"#MAX-UNSTABLE"

#define HELPLOC		"#HELPAREA"
#define MSGLOC		"#MSGAREA"
#define MSG2LOC		"#MSG2AREA"
#define LOGLOC		"#LOGAREA"
#define ROOMLOC		"#ROOMAREA"
#define FLOORLOC	"#FLOORAREA"
#define INFOLOC		"#INFOAREA"
#define AUDITLOC	"#AUDITAREA"
#define HOLDLOC		"#HOLDAREA"
#define BIOSLOC		"#BIOAREA"

#define MSGK		"#MESSAGEK"
#define LOGSIZE		"#LOGSIZE"
#define ROOMSIZE	"#MAXROOMS"
#define MSGS_PERROOM	"#MSG-SLOTS"
#define PMAILSLOTS	"#MAIL-SLOTS"

#define FGROUND		"#FOREGROUND"
#define BGROUND		"#BACKGROUND"
#define SFGROUND	"#STATUS-FOREGROUND"
#define SBGROUND	"#STATUS-BACKGROUND"

#define PCLOCK		"#CLOCK"
#define LOCKPORT	"#LOCK-PORT"

#define EVENT		"#event"
